apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cloudflare-tunnel.yaml
patches:
  - target:
      kind: Deployment
      name: backend-deploy
    path: backend-spot-patch.yaml
secretGenerator:
  - name: cloudflare-tunnel-secret
    envs:
      - ./.secret.cloudflare
