apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cloudflare-tunnel.yaml
secretGenerator:
  - name: cloudflare-tunnel-secret
    envs:
      - ./.secret.cloudflare
