"""Place Table: Use geography instead of geometry

Revision ID: 8d16c0508c08
Revises: 7ea8425668d0
Create Date: 2024-08-27 14:27:23.595574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "8d16c0508c08"
down_revision: Union[str, None] = "7ea8425668d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "place",
        "coordinate",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geography(
            geometry_type="POINT",
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "place",
        "coordinate",
        existing_type=geoalchemy2.types.Geography(
            geometry_type="POINT",
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
