apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - nginx-welcome.yaml
configMapGenerator:
  - name: nginx-reverse-proxy-config
    behavior: replace
    files:
      - nginx.conf
