apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    label: nginx-pod
  type: ClusterIP
  ports:
    - port: 80 # Expose the service on internal cluster IP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      label: nginx-pod
  template:
    metadata:
      labels:
        label: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.27
          ports:
            - containerPort: 80 # Expose the container on port 80
          resources:
            requests: # (50m, 52Mi) is the minimum request for autopilot burstable
              cpu: "50m"
              memory: "52Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
