apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    label: postgres-pod
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  selector:
    matchLabels:
      label: postgres-pod
  template:
    metadata:
      labels:
        label: postgres-pod
    spec:
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres-container
          image: postgis/postgis:16-3.4
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # PGDATA
              name: postgres-volume
          env: # Environment variables
            - name: POSTGRES_USER
              value: "superuser"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "database"
            # Below is used by psql
            - name: PGUSER
              value: "superuser"
            - name: PGDATABASE
              value: "database"
            - name: PGPORT
              value: "5432"
          ports:
            - containerPort: 5432 # Expose the container on port 5432
          resources:
            requests:
              cpu: "50m"
              memory: "52Mi"
            limits: # Need some resoures for postgis install (Accurate value is not tested)
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
